config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :teams
  resources :superheroes

  resources :users do
    resources :teams
    resources :superheroes, only: [:index, :new, :show, :create, :edit, :update, :destroy]
  end

  post "/users/:id/teams/:id/edit", to: "teams#edit"

  root "users#new"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  delete "/logout", to: "sessions#destroy"

  get '/auth/:provider/callback', to: 'sessions#facebookAuth'
  get '/auth/failure', to: redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/superhero.rb
class Superhero < ApplicationRecord
    belongs_to :user
    has_many :superhero_teams
    has_many :teams, through: :superhero_teams
    has_many :superpowers

    validates_presence_of [:name, :teams, :superpowers]

    accepts_nested_attributes_for :teams, reject_if: :all_blank
    accepts_nested_attributes_for :superpowers, reject_if: :all_blank

    def teams_attributes=(team_attributes)
        team_attributes.values.each do |team_attribute|
          team = Team.find_or_create_by(team_attribute)
          self.teams << team
        end
   end
    
end

app/models/superhero_team.rb
class SuperheroTeam < ApplicationRecord
    belongs_to :superhero
    belongs_to :team
end
  

app/models/superpower.rb
class Superpower < ApplicationRecord
    belongs_to :superhero
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :superhero_teams
    has_many :superheroes, through: :superhero_teams

    validates_uniqueness_of :name
    validates_presence_of :name

    def self.team_with_most_superheroes
        self.joins(:superheroes).group('superheroes.id').order("count(superheroes.id) DESC")
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :superheroes
    has_many :teams, through: :superheroes

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true
    validates :password, length: {minimum: 5}
    has_secure_password


    def self.g_random_code(number)
        array = Array('A'..'Z') + Array('a'..'z')
        Array.new(number) { array.sample }.join
    end      

    def self.from_omniauth(auth)
        # Creates a new user only if it doesn't exist
        where(email: auth.info.email).first_or_initialize do |user|
            user.email = auth.info.email
            user.username = auth.info.name + rand(1..1000).to_s
            user.name = auth.info.name
            password = self.g_random_code(19)
            user.password = password
        end
    end

    def teams_attributes=(team_attributes)
        team_attributes.values.each do |team_attribute|
          team = Team.find_or_create_by(team_attribute)
          self.teams << team
        end
    end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :redirect_if_not_logged_in
	helper_method :current_user

	private
	
	def logged_in?
		!!current_user
	end

	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end

	def redirect_if_not_logged_in
		if !logged_in?
			redirect_to login_path
		end
	end

	def new_user_or_go_to_user_path
		 if logged_in? 
			redirect_to user_path(current_user)
		 else @user = User.new
            render :layout => false 
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        new_user_or_go_to_user_path  
    end

    def create
        @user = User.find_by(username: params[:username])     
        if @user && @user.authenticate(params[:password])
			log_in(@user)
            redirect_to @user
        else
            flash[:notice] = "Incorrect Username or Password"
			redirect_to login_path
		end
	end

    def destroy
        session.clear
        redirect_to login_path
	end

	def facebookAuth
        # Get access tokens from the google server
        access_token = request.env["omniauth.auth"]
        @user = User.from_omniauth(access_token)
        # Access_token is used to authenticate request made from the rails application to the google server
        @user.facebook_token = access_token.credentials.token
        # Refresh_token to request new access_token
        # Note: Refresh_token is only sent once during the first request
        refresh_token = access_token.credentials.refresh_token
        @user.facebook_refresh_token = refresh_token if refresh_token.present?
       
        if @user.save
			log_in(@user)
            redirect_to user_path(@user)
        else
            redirect_to login_path
		end
    end

    
end

app/controllers/superheroes_controller.rb
class SuperheroesController < ApplicationController

    before_action :redirect_if_not_logged_in

    def index     
        @superheroes = current_user.superheroes 
        #binding.pry 
    end

    def show
        @superhero = Superhero.find(params[:id]) 
           
    end

    def new
        @superhero = Superhero.new      
    end

    def create
        @superhero = Superhero.new(superhero_params.merge(user_id: current_user.id))  
        if @superhero.save     
            redirect_to user_superheroes_path(current_user)
        else   
            render :new 
        end
    end

    def edit
        @superhero = Superhero.find(params[:id])            
    end

    def update
        @superhero = Superhero.find(params[:id])
        if @superhero.update(superhero_params)
            redirect_to user_superheroes_path(current_user)
        else
            render :edit
        end
    end 

    def destroy
        @superhero = Superhero.find(params[:id])
        @superhero.delete
        redirect_to user_superheroes_path(current_user)    
    end

    private

    def superhero_params
        params.require(:superhero).permit(:id, :name, :user_id, team_ids:[], teams_attributes: [:id, :name], superpowers_attributes: [:id, :name]) #need to use :id, so the fields in form do no duplicate/add new one instead of update existing
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def show
        @team = Team.team_with_most_superheroes
        #binding.pry
    end

    def edit
        @team = Team.find(params[:id])       
    end

    def update
        @team = Team.find(params[:id])
        if @team.update(team_params)
            redirect_to user_superheroes_path(current_user)    
        else
            render :edit
        end
    end

    def destroy
        @team = Team.find(params[:id])
        @team.delete
        @team.superheroes.destroy_all
        
        redirect_to user_superheroes_path(current_user)
    end


    private

    def team_params
        params.require(:team).permit(:id, :name)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new     
        new_user_or_go_to_user_path 
    end

    def create
        @user = User.new(user_params)
        if @user.save
          log_in(@user)  
          redirect_to @user 
        else
          render :new, layout: false
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find(params[:id])   
    end

    private

    def user_params
        params.require(:user).permit(:username, :name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
    <div style='color:red'>
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
    <ul>
        <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
    </ul>
    </div>
<% end %> 

app/views/layouts/_navbar.html.erb
<header>
    <nav class="navbar" style="background-color: #e3f2fd; padding-right: 2rem; text-decoration: none;">
        <a><%=link_to "Home", user_path(current_user.id) %></a>
        <a><%=link_to "Create a New Superhero", new_superhero_path %></a>
        <a><%=link_to "All Superheroes", superheroes_path %></a>
        <a><%=link_to "Team With the Most Superheroes", "/teams/:team_with_most_superheroes"%></a>
        <a><%=link_to "Logout", logout_path %></a>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperHero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <%= yield %>

  </body>
</html>

app/views/superheroes/_form.html.erb
<div class="container bootstrap snippets bootdey">
<div class="lc-block col-md-4 col-md-offset-4 toggled" id="l-login">
<div class="lcb-float"><i class="fa fa-users"></i></div>
<div class="form-group">
<h1>CREATE A SUPERHERO</h1>

<%= form_for(@superhero) do |f| %>

    <%= render partial: "layouts/error", locals: {object: @superhero} %>

    <div class="field">
      Superhero Name
      <%= f.text_field :name %>
      <br>
      <br>
    </div>

    <div class="field">
    <% if current_user.teams.exists? %>
        Select Team:
        <%= f.collection_check_boxes :team_ids, current_user.teams.uniq, :id, :name %>
        <br><br>
    <% end %>
    </div>

    <div class="field">
     Create a new Team:
      <%= f.fields_for :teams, @superhero.teams.build do |teams_fields| %>
        <%= teams_fields.text_field :name %>
      <% end %>
    </div>
    <br>
    
    <div class="field">
     Add Superpowers:
      <%= f.fields_for :superpowers, 3.times {@superhero.superpowers.build} do |superpower_fields| %>
      <br>
        <%= superpower_fields.text_field :name, placeholder: "Enter Superpower" %>
      <% end %>
    </div>
    
    <div class="actions">
    <br>
      <%=  f.submit class: "btn btn-block btn-primary btn-float m-t-25" %>
    </div>
  
<% end %>

</div>
</div>
</div>
</div>








<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

app/views/superheroes/edit.html.erb
<h1>EDIT SUPERHERO</h1>

<%= form_for(@superhero) do |f| %>

  <%= render partial: "layouts/error", locals: {object: @superhero} %>

  <div class="field">
    Superhero Name
    <%= f.text_field :name %>
    <br>
    <br>
  </div>
      
  <div class="field">
   Add Superpowers:
    <%= f.fields_for :superpowers, @superhero.superpowers do |superpower_fields| %>
    <br>
      <%= superpower_fields.text_field :name, placeholder: "Enter Superpower" %>
    <% end %>
  </div>
  
  <div class="actions">
  <br>
    <%= f.submit %>
  </div>

<% end %>

<%=button_to "Delete Superhero", user_superhero_path(current_user, @superhero), method: 'delete' %>

app/views/superheroes/index.html.erb
<% if current_user.teams.empty? || current_user.superheroes.empty?%>
    <h3>You do not have any superheroes, please click <%= link_to 'here', new_user_superhero_path(current_user) %> to create your superheroes </h3>
<% end %>  

<% current_user.teams.uniq.each do |team| %>
    
    <div class="team">
    <h2><%= team.name %></h3> <%=button_to "Edit/Delete Team", edit_user_team_path(current_user, team), {class: "btn btn-block btn-primary btn-float m-t-25"} %>
    </div>
    
    <div class="superhero">
        <% team.superheroes.each do |superhero| %>     
            <span class="superhero-name"><%= superhero.name %></span> <%=link_to "Edit/Delete Superhero", edit_user_superhero_path(current_user, superhero), {class: "edit-link"} %> 
            <% superhero.superpowers.each do |superpower| %>
                <li class='superpower'><%= superpower.name %></li>
            <br>
        <% end %>      
    <% end %>
    </div>

<% end %>

app/views/superheroes/new.html.erb
<%= render partial: "form"  %>

app/views/users/new.html.erb
<div class="log-in">
<h1>Welcome to Superhero Maker!</h1>
<br>
<h3>Sign Up Below</h3>
<button type="button" class="btn btn-primary btn-lg">Large button</button>

<%= form_for(@user) do |f| %>

    <%= render partial: "layouts/error", locals: {object: @user}  %>
    
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br/>
  
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br/>
  
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br/>
  
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br/>
  
    <%= f.submit 'Signup' %>

    <p>Already have an account? Log in <%= link_to "here", login_path %></p>

<% end %> 
</div>

app/views/users/show.html.erb
<h1>Hello, <%= current_user.name %></h1>